if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$")
    set(arch "x86_64")
elseif(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
    set(arch "aarch64")
else()
    message(FATAL_ERROR "Unsupported architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
endif()

# Get system triple
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(host_triple "${arch}-unknown-linux-gnu")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    if(arch STREQUAL "aarch64")
        set(host_triple "arm64-apple-macos")
    else()
        set(host_triple "x86_64-apple-macos")
    endif()
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(host_triple "${arch}-pc-windows-msvc")
else()
    message(FATAL_ERROR "Unsupported system: ${CMAKE_HOST_SYSTEM_NAME}")
endif()
