if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64)$")
    set(ARCH "x86_64")
elseif(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
    set(ARCH "aarch64")
else()
    message(FATAL_ERROR "Unsupported architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR}")
endif()

# Get system triple
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(HOST_TRIPLE "${ARCH}-unknown-linux-gnu")
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
    if(ARCH STREQUAL "aarch64")
        set(HOST_TRIPLE "arm64-apple-darwin")
    else()
        set(HOST_TRIPLE "x86_64-apple-darwin")
    endif()
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
    set(HOST_TRIPLE "${ARCH}-pc-windows-msvc")
else()
    message(FATAL_ERROR "Unsupported system: ${CMAKE_HOST_SYSTEM_NAME}")
endif()
