config_setting(
    name = "opt",
    values = {
        "compilation_mode": "opt",
    },
)

config_setting(
    name = "dbg",
    values = {
        "compilation_mode": "dbg",
    },
)

config_setting(
    name = "fastbuild",
    values = {
        "compilation_mode": "fastbuild",
    },
)
