load("@rules_foreign_cc//foreign_cc:defs.bzl")
load("defs.bzl", "TARGETS", "cross_compile_flags")
load("@bazel_skylib//:selects.bzl", "selects")

[
    selects.config_setting_group(
        name = target,
        match_all = 

[
    for target in TARGETS
]
