set(LLVM_ENABLE_PER_TARGET_RUNTIME_DIR  ON  CACHE BOOL "")
set(COMPILER_RT_BUILD_BUILTINS          OFF CACHE BOOL "")
set(COMPILER_RT_DEFAULT_TARGET_ONLY     ON  CACHE BOOL "")
set(COMPILER_RT_USE_LIBCXX              OFF CACHE BOOL "")

# Workaround for https://github.com/llvm/llvm-project/issues/57717
set(COMPILER_RT_BUILD_GWP_ASAN OFF CACHE BOOL "")

set(CMAKE_BUILD_WITH_INSTALL_RPATH ON CACHE BOOL "")
