set(LIBOMP_CXXFLAGS "-fPIC -fvisibility=hidden -fvisibility-inlines-hidden" CACHE STRING "")
set(OPENMP_LLVM_TOOLS_DIR ${LLVM_TOOLS_DIR} CACHE STRING "")
set(LIBOMP_ENABLE_SHARED       OFF CACHE BOOL "")
set(LIBOMP_OMPD_GDB_SUPPORT    OFF CACHE BOOL "") # requires python
set(OPENMP_ENABLE_LIBOMPTARGET OFF CACHE BOOL "")

set(CMAKE_BUILD_WITH_INSTALL_RPATH ON CACHE BOOL "")
